### ISSUE TITLE
World unloads when looking at a villager with The One Probe equipped.

### ISSUE THREAD

**Issue by belathus** [McJty/TheOneProbe#104]
http://pastebin.com/mZAM1aBG

It looks almost like Esteemed Innovation does something to villagers that causes this 'crash'?

**Comment by McJty** [comment]
Yes this looks like a bug in Esteemed Innovation

**Comment by elifoster** [comment]
It's because `VillagerDataStorage#writeNBT` can return null if the value in `VillagerData` has not been set yet (I tried returning a new NBTTagCompound instead as a test and it didn't crash). There isn't really much I can do to avoid that, and returning null in `writeNBT` is standard behavior for `Capability.IStorage`s, as mentioned in its docs:

>`* @return a NBT holding the data. Null if no data needs to be stored.`

Do you have some nonnull assumptions in the data info code or something @McJty ?

**Comment by McJty** [comment]
I'll check it out. I missed that there are multiple crash reports unrelated to this issue in that log
