### ISSUE TITLE
Show IItemHandler data in default block provider

### ISSUE THREAD

**Issue by falkreon** [McJty/TheOneProbe#127]
Since TOP now uses forge's built-in IEnergyStorage, it's probably time to add support for the built-in IItemHandler. Some mod blocks don't extend BlockContainer or IInventory/ISidedInventory, and could benefit from a capabilities-based view.

**Comment by exaskye** [comment]
It looks like [this *is* supported](https://github.com/McJty/TheOneProbe/blob/7d655fb3aeb2d08c4b09f287a6c0d0c09b2f7286/src/main/java/mcjty/theoneprobe/apiimpl/providers/ChestInfoTools.java#L117), but only if you have a cap for null, i.e. "no face".

Which is kind of strange because you have to look at a specific face of the block, there's no way with TOP to get info on a block without looking at it... is there?

**Comment by McJty** [comment]
TOP is supposed to show the internal information. i.e. if you look at a furnace I want TOP to show all the available items in the furnace and not just the one accessible from the side that you're looking at. That's why TOP does it like this.

The face for null is something mod authors should support. That's what this is for
