### ISSUE TITLE
Forestry doors showing unlocalized name

### ISSUE THREAD

**Issue by JaSpr** [McJty/TheOneProbe#137]
[Cherry Door](http://i.imgur.com/ny4fnXf.png)
[Teak Door](http://i.imgur.com/w6ykJWv.png)

**Comment by McJty** [comment]
Versions please?

**Comment by JaSpr** [comment]
Man, I'm an idiot.

TOP 1.1x-1.4.2
Forestry 5.2.17.362
MC 1.10.2

**Comment by McJty** [comment]
@mezz, any idea what I could be doing wrong? I do the localization on the client now and from the server I sent over unlocalized names for the itemstack

**Comment by mezz** [comment]
Forestry has complex localization that often involve multiple localization keys and grammar, it needs more than just the localization string. I think you will have to serialize the ItemStack so that it can localize itself on the client.

I override `Item#getItemStackDisplayName` here:
https://github.com/ForestryMC/ForestryMC/blob/mc-1.11/src/main/java/forestry/arboriculture/items/ItemBlockWood.java

And this is the localization code:
https://github.com/ForestryMC/ForestryMC/blob/mc-1.11/src/main/java/forestry/arboriculture/WoodHelper.java#L24

**Comment by McJty** [comment]
Hmm, transmitting ItemStacks could potentially give big network overhead. Especially if getPickBlock for some block returns a very heavy itemstack. I was hoping for a lighter solution but I guess it will not be easy

**Comment by mezz** [comment]
It will definitely be more overhead than before, but one ItemStack per player per tick (worst case?) is still not very much is it? It may be the only way to be fully-compatible with mods that override `getItemStackDisplayName`. If you want to test a very heavy block, try Forestry saplings because they have NBT stored on them for genetics and it is preserved by getPickBlock.

**Comment by McJty** [comment]
Fixed next version
