### ISSUE TITLE
[1.12] Config GUI Broken

### ISSUE THREAD

**Issue by SnowShock35** [McJty/TheOneProbe#179]
Hi @McJty,

I believe I have found an issue with The One Probe in Minecraft 1.12, here's the details:

### Issue Information 

- Minecraft 1.12
- Minecraft Forge 14.21.1.2387
- The One Probe 1.4.11

### Issue Description

The In-Game config GUI added by Forge no longer is accessible via the game. 

### Issue Media

![](https://ss.blamesnow.co.uk/2017/06/1498735538-350ef09c.png)
![](https://ss.blamesnow.co.uk/2017/06/1498735553-1793ba76.png)

**Comment by McJty** [comment]
I wonder if that's my bug or a bug in forge as I didn't actually touch that

**Comment by SnowShock35** [comment]
Hmm. It's possible that the way to register it or the deprecated methods in GUIFactory were finally removed. Not quite sure really. 😕

**Comment by tomelfring** [comment]
I've read some PSA from Mezz about changed methods regarding background drawing.
I'm not sure that this is the same, but sounds related.


mezz> 1.12 PSA: by default your guis will not draw with a black background because... reasons I guess??? easy fix but very easy to miss it. https://github.com/ForestryMC/ForestryMC/commit/39290512cffb1bd1e79b5df8fd074a9fcd43ffe6

**Comment by McJty** [comment]
Fixed next release
