### ISSUE TITLE
Suggestion: option to change harvest level display

### ISSUE THREAD

**Issue by MauveCloud** [McJty/TheOneProbe#224]
The way harvest levels are shown now is potentially confusing - I've read the other bugs (such as #174) claiming these were "wrong", and your explanation of how it was based on what it could mine, but that's not entirely obvious when first using the mod.  Also, in 1.7.10, TConstruct used "Redstone" as the harvest level for blocks that require a pickaxe made from iron (or same tier, such as bronze), which had slightly less risk of confusion, while https://github.com/McJty/TheOneProbe/blob/1.12/src/main/java/mcjty/theoneprobe/apiimpl/providers/HarvestInfoTools.java shows that TOP is hard-coded to show entries that are pretty much all also potential tool materials (obsidian is a vanilla material, so its presence doesn't automatically mean I have a mod that allows making tools from it, but if I've got a mod that adds cobalt, I'm pretty sure it will be available as a tool material (although GT5u treats cobalt material as tier 3 instead of tier 4 like TiCon does).

Personally, I'd rather see the harvest level as a number, possibly preceded by "level" or "tier" or something.  https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/utils/HarvestLevels.java shows that TiCon pulls the Harvest Levels from a lang file, so I could presumably set up a resource pack with a lang file to show the harvest levels differently for that mod, but as far as I can tell, TOP currently provides no such functionality.

**Comment by Zygus42** [comment]
Yep.  Very confusing - especially for new players.  If I point at an iron ore block with an empty hand, it has a red x and says pickaxe (iron).  For me, I would take this to mean that I would need at least an iron pickaxe to harvest this block.  However, when I have a stone pickaxe in my hand, it has a green tick with just the word pickaxe next to it.  I personally understand that this is because the stone pickaxe has a mining level of "iron", but it's still very confusing.  Perhaps if it said "pickaxe (iron mining lvl)" or pickaxe (stone or better) it would be clearer ?

**Comment by Zygus42** [comment]
Just started a new server with one probe, and had a question from EVERY single player where they thought the game was broken because of the way this info is displayed.

**Comment by McJty** [comment]
I'll try to come up with a better way to formulate this

**Comment by McJty** [comment]
Proposals. When looking at an iron ore block:

- Tool: pickaxe with mining level iron
- Tool: pickaxe (mining level at least iron)
- Tool: iron pickaxe (or better)

What would be best? Any others?

**Comment by MauveCloud** [comment]
> Tool: iron pickaxe (or better)

When looking at an iron ore block?  afaik, the only iron ore that requires an iron pickaxe to mine is from GregTech.  Vanilla iron ore can be mined with a stone pickaxe.  However, this style looks shorter than the others (at least in English), so I like it as a default.  I still advocate having a config (or lang file) to allow players to change how this is displayed, especially for tiers 4 and up, where the tool materials available may vary depending on what mods are installed.

**Comment by McJty** [comment]
Sorry I meant, when looking at a block that requires an iron pickaxe to mine

**Comment by Zygus42** [comment]
Out of those I would pick:
pickaxe with mining level iron

or

pickaxe (iron mining lvl)

or

pickaxe (stone or better)

**Comment by McJty** [comment]
I simply added the word 'level'. I had a poll on twitter and opinions were divided. Many even opted to keep it as it is

**Comment by ghost** [comment]
I think with simple variation options like this you should add options in the config similar to showBreakProgress where you could select between a few variations, giving end-users the option to choose instead of a majority vote :) Could be implemented alongside https://github.com/McJtyMods/TheOneProbe/issues/223
