### ISSUE TITLE
1.10.2 TOP and enderio conflict. It cause the client to crash. Fix it please!

### ISSUE THREAD

**Issue by zsn741656478** [McJty/TheOneProbe#233]
crash report：http://paste.ubuntu.org.cn/4318393
When I delete the Top. Client can start.

**Comment by josephcsible** [comment]
I just created a clean instance with just Forge 2511, EnderCore 0.4.1.66, EIO 3.1.183, CompatLayer 0.3.1, and TOP 1.4.19, and it starts fine for me. Here's a few things to do to troubleshoot this:

* Your EnderIO version is out of date. Try updating to 3.1.193.
* If your game language isn't English (US), try temporarily changing it to that.
* See if you can reproduce the problem without all of the other mods, especially the coremods (OptiFine and everything listed at the top).
* It looks like you either have unofficial mod jars, or you renamed them all. Try using the original jars with their original names.
* The error says that "recipe_items_core.xml or recipe_items_user.xml" are bad files and that it "Could not find a crafting ingredient for 'crystalFluix' (stack=null, object=null) in recipe 'Conduit, ME'". Do either of those seem familiar? Did you change anything related to them? If so, try changing it back to the default.

Let me know what happens when you try each of those things.
