### ISSUE TITLE
Block info on multiparts

### ISSUE THREAD

**Issue by rubensworks** [McJty/TheOneProbe#30]
It does not seem to be possible to change the displayed ItemStack when hovering over a Block. This behaviour comes from the `DefaultProbeInfoProvider`, which can not be overridden as far as I know.
Example:
![2016-07-26_18 04 24](https://cloud.githubusercontent.com/assets/440384/17145683/76cb87c2-535b-11e6-9d4c-aff7e5617d2c.png)

Currently, the `DefaultProbeInfoProvider` selects the ItemStack from the IBlockState [without taking into account the player's look vector]((https://github.com/McJty/TheOneProbe/blob/f5d4241f63665a40344db498b42716400e0bfbbe/src/main/java/mcjty/theoneprobe/apiimpl/DefaultProbeInfoProvider.java#L82)).
This means that no different item can be displayed for multiparts.

My suggestion would be to use `Block#getPickBlock` to retrieve the ItemStack to display, which includes a look vector.

**Comment by McJty** [comment]
Actually the one probe already uses getPickBlock. Not sure why it wouldn't be working though

**Comment by rubensworks** [comment]
Ah I see, you're right. Apparently I was looking in the wrong branch, where `getPickBlock` was not in use yet. I'll do some debugging to figure out where the problem is.

**Comment by McJty** [comment]
Thanks, that's appreciated

**Comment by rubensworks** [comment]
I managed to partially fix this problem in #31.
You can now see the different parts in Integrated Dynamics blocks (This is a system separate from McMultiPart)
![2016-07-27_11 41 36](https://cloud.githubusercontent.com/assets/440384/17171120/8759c416-53ef-11e6-84bd-c1088a16db85.png)

The problem with McMultiPart itself still remains however.
This seems to be caused by the fact that the base MCMP block requires the `RayTraceResult` to be an instance of `PartMOP`: https://github.com/amadornes/MCMultiPart/blob/1.9/src/main/java/mcmultipart/block/BlockMultipartContainer.java#L131
It think this is done for caching reasons.
But since TOP creates new instances of `RayTraceResult`, this will never work.
And since clients get TOP data from a server, new instances of `RayTraceResult` must be created and the original instances from `Block#collisionRayTrace` simply can not be used.

One easy solution would be to add explicit support for MCMP blocks.

@amadornes, maybe you have an idea on how to solve this issue?

**Comment by amadornes** [comment]
Huh... Why does it re-create the raytrace result object? O_o

**Comment by rubensworks** [comment]
I think he does that because the raytrace data is sent to the server, the server determines then determines the data to show, which is then sent back to the client. (If I understand correctly)

**Comment by amadornes** [comment]
Huh... Okay... I'd suggest another protocol for that that would be much safer, though that'd involve API changes. Instead of unpacking the data and sending it to the server, to then process it and send it back to the client, you'd be asked to provide an NBT tag with the data you care about in the client, which would be serialized and sent to the server, where it'd be passed through a handler that would give you another NBT tag with all the right info. This tag would then be sent to the client and processed in order to give you a graphical representation of the data. Alternatively, devs could opt-out of all the networking mess (probably even opt-in) and just handle it all clientside :P

**Comment by McJty** [comment]
I really don't want to change the way this works so drastically. That's not how this mod is supposed to work really. Why exactly can getPickBlock not work with custom made RayTraceResults? Seems to me by doing that you're asking for other problems. getPickBlock() might be used with other dummy RayTraceResult instances that aren't a direct result of a client hitbeam.

**Comment by McJty** [comment]
Also the getPickBlock() API doesn't specify that RayTraceResult has to be any specific implementation. This should be able to work with any RayTraceResult to be conform to that API

**Comment by amadornes** [comment]
Not really. Especially because I store the multipart and box that were hit in separate fields inside of PartMOP. If CB's multipart API was still a thing you'd be running into the exact same issue. RayTraceResult isn't made to be serialized and deserialized like this. If it were, it'd have some kind of serialization methods built in. Also, how do you send RayTraceResult#hitInfo? There's no way for you to do that and it's a field that pretty much all mods that do any kind of custom raytracing use. Plus, raytracing on the server is kinda... meh. It's mostly meant for clientside applications. That's why vanilla doesn't send the hit result to the server when you break a block nor does it retrace it, it just sends the position you're breaking. Since there's always a 1 (or more) tick desync between the client and the server, the raytrace result doesn't match in both sides, which is why if you're moving and break a multipart it's possible that you'll end up breaking the wrong one (we're working on a solution for the FMP that we'll be in Forge). So yeah... I really don't recomend raytracing on the server. It's not meant for that and some people actually call clientside only methods from there and fall back to a full raytrace result with no data if it's a server raytrace. That said, changing the API isn't the best option either, but even though I haven't looked at it I doubt it'd be *too* hard to adapt.

**Comment by McJty** [comment]
Ok. I'll think about a solution that doesn't require changing the API

**Comment by McJty** [comment]
Fixed now
