### ISSUE TITLE
Issue with Mekanism tanks <=n=>Liquid: Water

### ISSUE THREAD

**Issue by fred21O4** [McJty/TheOneProbe#487]
When using TheOneProbe 1.16-3.1.3 with mekanism-1.16.5-10.0.21.488 If I look at a tank while sneaking I get this
![image](https://user-images.githubusercontent.com/67189813/118899472-ebdd1400-b962-11eb-957f-ca941fde31f9.png)

**Comment by fred21O4** [comment]
also happens with immersive engineering 
![image](https://user-images.githubusercontent.com/67189813/118904107-4bd8b800-b96d-11eb-9c7b-472ccfe13a2e.png)

**Comment by Speiger** [comment]
Yeah the reason is i implemented support for proper TextRendering into OneProbe.
But made sure that if you make a CompoundText (the raw string what you reported as a bug) is still supported.
But detecting that if it is a old or new renderer is not perfect. I should have splitten them up into dedicated functions.

So what causes this bug: They create a compound text but use the normal text render method instead of the compound method.
The compound method is still using the old system because it has to, but the normal text method uses the new system.

Both mods can fix this by removing a "get" function or we can fix this by making dedicated functions for the new renderer and marking the old renderer as depricated. May have been the better solution.

**Comment by McJty** [comment]
I think compatibility is important so it's probably better to do the second option

**Comment by Speiger** [comment]
then add new text functions into the the one probe api thats called maybe "mcText" and they dont call the setLegacy function while the normal text ones do call "setLegacy"

**Comment by Speiger** [comment]
https://github.com/McJtyMods/TheOneProbe/blob/1.16/src/main/java/mcjty/theoneprobe/apiimpl/elements/AbstractElementPanel.java#L117

All the normal text functions just need the "setLegacy" thats it.

**Comment by McJty** [comment]
Should be fixed now
