### ISSUE TITLE
Appears broken on SMP servers

### ISSUE THREAD

**Issue by Repo-Meister** [McJty/TheOneProbe#531]
I only have a few other mods installed and I removed them all but your mod which is just a simple client-side mod that does nothing but display client-side data to the user stopped working when playing a server. I am going crazy trying to figure this out. It works fine in a single-player world as it should since all it does is show client-side info. Like FFS - just SHOW ME what block I am looking at! Why would this stop working on an SMP server?  Please help - the insanity is weighing on me.

**Comment by McJty** [comment]
Version please? Also logs

**Comment by TainanRezende** [comment]
> Versão por favor? Também registra

I'm having a similar problem on my server but with the information display of mekanism blocks
![Captura de tela 2022-01-13 082146](https://user-images.githubusercontent.com/86209504/149321129-ced54106-f8f7-486a-a562-e07be1f3d9b3.png)

sica waiting and never appears other information

mod version: 1.3.4

**Comment by McJty** [comment]
First TOP is not a client side mod. TOP is server side too. Don't forget that. So TOP has to be installed on the server

**Comment by TainanRezende** [comment]
> First TOP não é um mod do lado do cliente. TOP também é do lado do servidor. Não se esqueça disso. Então o TOP tem que ser instalado no servidor

no meu caso ele esta em ambos os lados tanto no server quanto no client, e se ajuda o servidor quando inicia essa mensagem no pronpt:

[13Jan2022 07:52:25.647] [Thread-1/FATAL] [mcjty.theoneprobe.TheOneProbe/CORE]: theoneprobe config just got changed on the file system!
[13Jan2022 07:52:25.648] [Thread-1/FATAL] [mcjty.theoneprobe.TheOneProbe/CORE]: theoneprobe config just got changed on the file system!

**Comment by TainanRezende** [comment]
> First TOP is not a client side mod. TOP is server side too. Don't forget that. So TOP has to be installed on the server

in my case it is on both sides of both the server and the client, and it helps the server when it starts this message in the prompt:

[13Jan2022 07:52:25.647] [Thread-1/FATAL] [mcjty.theoneprobe.TheOneProbe/CORE]: theoneprobe config just got changed on the file system!
[13Jan2022 07:52:25.648] [Thread-1/FATAL] [mcjty.theoneprobe.TheOneProbe/CORE]: theoneprobe config just got changed on the file system!

**Comment by McJty** [comment]
That's fine. But 'waiting for server' is not a problem with TOP. It just means the server is lagging but that lag is not caused by top

**Comment by TainanRezende** [comment]
> Isso é bom. Mas 'aguardar servidor' não é um problema com o TOP. Significa apenas que o servidor está atrasado, mas esse atraso não é causado por top


I opened modpack through technic and got this error that appears in the prompt when I look at mekanism items
if you can tell me if it is your mod or where it is pointing (mod) this error there I try to solve it with the mod that is being pointed



[10:55:26.518] [main/FATAL] [concurrent.ThreadTaskExecutor/]: Error executing task on Client io.netty.handler.codec.EncoderException: java.io.EOFException: fieldSize is too long! Length is 65535, but maximum is 43
[B#709]  	at net.minecraft.network.PacketBuffer.func_244272_a(PacketBuffer.java:284) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:packetsizelimits.PacketBufferMixin,pl:mixin:A}
[B#709]  	at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:264) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:packetsizelimits.PacketBufferMixin,pl:mixin:A}
[B#709]  	at net.mrscauthd.boss_tools.gauge.GaugeValueSerializer.read(GaugeValueSerializer.java:48) ~[?:1.0] {re:classloading}
[B#709]  	at net.mrscauthd.boss_tools.gauge.GaugeValueRenderer.<init>(GaugeValueRenderer.java:18) ~[?:1.0] {re:classloading}
[B#709]  	at net.mrscauthd.boss_tools.compat.theoneprobe.GaugeValueElement.<init>(GaugeValueElement.java:15) ~[?:1.0] {re:classloading}
[B#709]  	at net.mrscauthd.boss_tools.compat.theoneprobe.ProbeInfoProvider$$Lambda$27355/1744457113.createElement(Unknown Source) ~[?:?] {}
[B#709]  	at mcjty.theoneprobe.apiimpl.ProbeInfo.createElements(ProbeInfo.java:28) ~[?:1.16-3.1.4] {re:classloading}
[B#709]  	at mcjty.theoneprobe.apiimpl.ProbeInfo.fromBytes(ProbeInfo.java:15) ~[?:1.16-3.1.4] {re:classloading}
[B#709]  	at mcjty.theoneprobe.network.PacketReturnInfo.<init>(PacketReturnInfo.java:25) ~[?:1.16-3.1.4] {re:classloading}
[B#709]  	at mcjty.theoneprobe.network.PacketHandler$$Lambda$24009/497599627.apply(Unknown Source) ~[?:?] {}
[B#709]  	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:120) ~[?:?] {re:classloading}
[B#709]  	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$28342/171866050.apply(Unknown Source) ~[?:?] {}
[B#709]  	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51] {}
[B#709]  	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:120) ~[?:?] {re:classloading}
[B#709]  	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?] {re:classloading}
[B#709]  	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:forge.SimpleChannelMixin,pl:mixin:A}
[B#709]  	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2869/1078027041.accept(Unknown Source) ~[?:?] {}
[B#709]  	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
[B#709]  	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
[B#709]  	at net.minecraftforge.eventbus.EventBus$$Lambda$2871/645038677.invoke(Unknown Source) ~[?:?] {}
[B#709]  	at net.minecraftforge.eventbus.EventBus$$Lambda$3053/527148155.invoke(Unknown Source) ~[?:?] {}
[B#709]  	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
[B#709]  	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
[B#709]  	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[?:?] {re:classloading}
[B#709]  	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[?:?] {re:classloading}
[B#709]  	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$28333/1098863555.apply(Unknown Source) ~[?:?] {}
[B#709]  	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51] {}
[B#709]  	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[?:?] {re:classloading}
[B#709]  	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
[B#709]  	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?] {re:classloading}
[B#709]  	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?] {re:classloading}
[B#709]  	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
[B#709]  	at net.minecraft.network.PacketThreadUtil$$Lambda$28641/1192985018.run(Unknown Source) ~[?:?] {}
[B#709]  	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[B#709]  	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:mixin,re:computing_frames,re:classloading}
[B#709]  	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[B#709]  	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
[B#709]  	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:magnesium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:magnesium.mixins.json:features.gui.MixinMinecraftAccessor,pl:mixin:APP:mixins.malilib.json:MixinMinecraftClient,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:performant.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[B#709]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:magnesium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:magnesium.mixins.json:features.gui.MixinMinecraftAccessor,pl:mixin:APP:mixins.malilib.json:MixinMinecraftClient,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:performant.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[B#709]  	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
[B#709]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
[B#709]  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
[B#709]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
[B#709]  	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
[B#709]  	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.23-launcher.jar:36.2] {}
[B#709]  	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$515/2020725345.call(Unknown Source) [forge-1.16.5-36.2.23-launcher.jar:36.2] {}
[B#709]  	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
[B#709]  	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
[B#709]  	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
[B#709]  	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
[B#709]  	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
[B#709]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
[B#709]  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
[B#709]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
[B#709]  	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
[B#709]  	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52) [ForgeWrapper-1.5.1.jar:1.5.1] {re:classloading}
[B#709]  Caused by: java.io.EOFException: fieldSize is too long! Length is 65535, but maximum is 43
[B#709]  	at io.netty.buffer.ByteBufInputStream.checkAvailable(ByteBufInputStream.java:313) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
[B#709]  	at io.netty.buffer.ByteBufInputStream.readFully(ByteBufInputStream.java:233) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
[B#709]  	at java.io.DataInputStream.readUTF(DataInputStream.java:609) ~[?:1.8.0_51] {}
[B#709]  	at io.netty.buffer.ByteBufInputStream.readUTF(ByteBufInputStream.java:287) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
[B#709]  	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:113) ~[?:?] {re:classloading}
[B#709]  	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:87) ~[?:?] {re:classloading}
[B#709]  	at net.minecraft.network.PacketBuffer.func_244272_a(PacketBuffer.java:282) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:packetsizelimits.PacketBufferMixin,pl:mixin:A}
[B#709]  	... 55 more

**Comment by McJty** [comment]
Ok, that looks like a bug in Mekanism. They have to fix their TOP API support

**Comment by TainanRezende** [comment]
> Ok, that looks like a bug in Mekanism. They have to fix their TOP API support

ok, thank you very much and sorry for any work there, #betterMOD kkkkk

**Comment by gisellevonbingen** [comment]
i had some test with below code (from https://github.com/Space-BossTools/Space-BossTools/blob/1.16.5-2.0/src/main/java/net/mrscauthd/boss_tools/compat/theoneprobe/ProbeInfoProvider.java)
```java
@Override
public Void apply(ITheOneProbe top) {
	top.registerProvider(this);
	top.registerProbeConfigProvider(ProbeConfigProvider.INSTANCE);
	ELEMENT_ID = top.registerElementFactory(GaugeValueElement::new);
	System.out.println("ELEMENT_ID : " + ELEMENT_ID);
	System.out.println("ELEMENT_ID : " + ELEMENT_ID);
	System.out.println("ELEMENT_ID : " + ELEMENT_ID);
	System.out.println("ELEMENT_ID : " + ELEMENT_ID);
	System.out.println("ELEMENT_ID : " + ELEMENT_ID);
	System.out.println("ELEMENT_ID : " + ELEMENT_ID);
	System.out.println("ELEMENT_ID : " + ELEMENT_ID);
	System.out.println("ELEMENT_ID : " + ELEMENT_ID);
	System.out.println("ELEMENT_ID : " + ELEMENT_ID);
	System.out.println("ELEMENT_ID : " + ELEMENT_ID);

	return null;
}
```

I saw that 'ELEMENT_ID' was changed
in my guess, that problem maybe came from that value changed
![image](https://user-images.githubusercontent.com/44163945/149470927-420794e6-2ee4-46f4-864f-424f25a42f34.png)
1. https://gist.github.com/gisellevonbingen/818ebfe47dda6350c82acbce54be3710
1. https://gist.github.com/gisellevonbingen/ddb6174aef9a40d3c5f266b60f2ccb0e

test steps
1. remove 'world' in server directory
2. run mohist-1.16.5-897-server.jar (https://mohistmc.com/download)
3. check that 'ELEMENT_ID'

sometimes it changes, sometimes the same value
I don't change anything otherwise 'remove world directory'

client and server's mod list is same
client's value is always 18

do you know how to deal with this phenomenon?

**Comment by TainanRezende** [comment]
> Ok, that looks like a bug in Mekanism. They have to fix their TOP API support

possible cause of the problem (post above)
